In [1]:
import numpy as np
import sys

In [2]:
l = list(range(1000000))
print(sys.getsizeof(l))
%timeit l = list(range(1000000))

8000056
27 ms ± 689 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
arr = np.arange(1000000)
print(sys.getsizeof(arr))
%timeit arr = np.arange(1000000)

4000096
1.35 ms ± 26.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
l = tuple(range(1000000))
print(sys.getsizeof(l))
%timeit l = list(range(1000000))

8000040
27 ms ± 406 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
l =set(range(1000000))
print(sys.getsizeof(l))
%timeit l = list(range(1000000))

33554648
27.1 ms ± 329 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
l = [10,20,30,40,50]
m = []
for i in l:
    m.append(i+5)
print(m)

[15, 25, 35, 45, 55]


In [7]:
arr = np.array([10,20,30,40,50])
print(arr+5)

[15 25 35 45 55]


In [8]:
print(arr*5)

[ 50 100 150 200 250]


In [9]:
#Converting list to array
l = [10,20,30,40,50]
print(type(l))
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr.shape)

<class 'list'>
<class 'numpy.ndarray'>
(5,)


In [10]:
l = [[10,20,30,40,50],[ 50, 100 ,150 ,200, 250]]
arr = np.array(l)
print(arr)
print(arr.ndim)
print(arr.shape)


[[ 10  20  30  40  50]
 [ 50 100 150 200 250]]
2
(2, 5)


In [11]:
l = [10,20,30,40,50]
arr = np.array(l)
print(arr.dtype)

int32


In [12]:
l1 = [10,20,30,40,50.5]
arr = np.array(l1)
print(arr.dtype)

float64


In [13]:
l2 = [10,'20',30,40,50.5]
arr = np.array(l2)
print(arr.dtype)

<U11


In [14]:
l2 = [False]
arr = np.array(l2)
print(arr.dtype)

bool


In [15]:
arr = np.array([10,20,30,40,50.5],dtype='int64')
print(arr.dtype)

int64


In [16]:
#Different ways of creating numpy arrays
arr = np.array([10,20,30,40,50.5])
print(arr)

[10.  20.  30.  40.  50.5]


In [17]:
lst = [10,20,30,40,50.5]
arr = np.array(lst)
print(arr)

[10.  20.  30.  40.  50.5]


In [18]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
arr = np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
arr = np.ones((3,2,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [22]:
arr = np.full((3,2),4)
print(arr)

[[4 4]
 [4 4]
 [4 4]]


In [23]:
arr = np.full(10,25)
print(arr)

[25 25 25 25 25 25 25 25 25 25]


In [33]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
arr = np.arange(5,21)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [36]:
arr = np.arange(5,21,2)
print(arr)

[ 5  7  9 11 13 15 17 19]


In [37]:
#Numerical operations on Numpy

arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[10,20],[30,40]])


In [38]:
print(arr1+arr2)

[[110 220]
 [330 440]]


In [39]:
print(arr1-arr2)

[[ 90 180]
 [270 360]]


In [40]:
print(arr1*arr2)

[[ 1000  4000]
 [ 9000 16000]]


In [41]:
print(arr1//arr2)

[[10 10]
 [10 10]]


In [42]:
print(arr1/arr2)

[[10. 10.]
 [10. 10.]]


In [43]:
print(arr1%arr2)

[[0 0]
 [0 0]]


In [44]:
print(arr1<arr2)

[[False False]
 [False False]]


In [45]:
print(arr1>arr2)

[[ True  True]
 [ True  True]]


In [46]:
print(arr1==arr2)

[[False False]
 [False False]]


In [49]:
arr1 = np.array([[100,200],[300,400]])
arr2 = np.array([[10,20],[30,40,50]])

<ipython-input-49-8ff245074dd8>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr2 = np.array([[10,20],[30,40,50]])


In [50]:
print(arr1+arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [55]:
#slicing  of Numpy Array
lst = [10,20,30,40,50]
slice_lst = lst[1:4]
print(slice_lst)


[20, 30, 40]


In [56]:
slice_lst[1] = 300
print(slice_lst)

[20, 300, 40]


In [57]:
#Indexing of Numpy Array
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [58]:
print(arr[1])

[40 50 60]


In [59]:
print(arr[1][1])

50


In [60]:
print(arr[1,1])

50


In [61]:
print(arr[0:2])

[[10 20 30]
 [40 50 60]]


In [62]:
print(arr[:2])

[[10 20 30]
 [40 50 60]]


In [63]:
print(arr[0:2,1:3])

[[20 30]
 [50 60]]


In [64]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [66]:
print(arr[0,1])

20


In [70]:
arr2 = np.array([[10,20],[20,30],[30,40],[40,50],[50,60],[60,70],[70,80],[80,90]])
print(arr2)

[[10 20]
 [20 30]
 [30 40]
 [40 50]
 [50 60]
 [60 70]
 [70 80]
 [80 90]]


In [71]:
print(arr2[[1,2,3,4]])

[[20 30]
 [30 40]
 [40 50]
 [50 60]]


In [72]:
print(arr2[[6,4,5,2]])

[[70 80]
 [50 60]
 [60 70]
 [30 40]]


In [74]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [75]:
print(arr[arr%2==0])

[ 0  2  4  6  8 10 12 14]


In [76]:
print(arr[arr<8])

[0 1 2 3 4 5 6 7]


In [77]:
print(arr[arr%2!=0])

[ 1  3  5  7  9 11 13]


In [78]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [79]:
print(arr[[0,1,2],[0,2,1]])

[10 60 80]


In [80]:
#Transpose
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr.T)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [83]:
#Universal Functions in Numpy
arr = np.array([100,200,300,400])
print(arr)

[100 200 300 400]


In [84]:
print(np.sqrt(arr))

[10.         14.14213562 17.32050808 20.        ]


In [87]:
print(np.exp(arr))

[2.68811714e+043 7.22597377e+086 1.94242640e+130 5.22146969e+173]


In [88]:
arr1 = np.array([45,58,96,45,42,78])
arr2 = np.array([75,84,62,23,32,67])
print(np.maximum(arr1,arr2))

[75 84 96 45 42 78]


In [90]:
arr3 = np.array([10.5,20.3,64.2,98.2,35.2])
fractional,whole = np.modf(arr3)
print(fractional)
print(whole)

[0.5 0.3 0.2 0.2 0.2]
[10. 20. 64. 98. 35.]


In [ ]:
#Numpy using Zip
lst1 = [1,2,3,4,5,6,7,8,9]
lst2 = [1.1]